CREATE TABLE ConversionExtensior (
   ID        WORD,
   Extension VARCHAR,
   Parent    VARCHAR
);

CREATE INDEX;

INSERT INTO CompilateurExtensior VALUES (    6,'.C',  'C2PAS.EXE');
INSERT INTO CompilateurExtensior VALUES (    7,'.CAS','C2PAS.EXE');
INSERT INTO CompilateurExtensior VALUES (    9,'.CC', 'C2PAS.EXE');
INSERT INTO CompilateurExtensior VALUES (   11,'.CPP','C2PAS.EXE');
INSERT INTO CompilateurExtensior VALUES (   18,'.H',  'C2PAS.EXE');
INSERT INTO CompilateurExtensior VALUES (   20,'.HPP','C2PAS.EXE');
INSERT INTO CompilateurExtensior VALUES (   25,'.RC', 'RC2PAS.EXE');


