{ Cette unit‚ est utilis‚ pour programmer les menus du l'application
 ®MonsterBookЇ version Bureautique.
}

Unit MBBMenu;

{ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД}
                                  INTERFACE
{ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД}

{$DEFINE BureauVersion}
{$DEFINE Bureau}

{$I MBMenu.Inc}

{ДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД}
END.