CREATE TABLE Html2Ascii (
   ID     CHAR,
   Name   VARCHAR
);

CREATE INDEX;

INSERT INTO Html2Ascii VALUES ('é','Auml');
INSERT INTO Html2Ascii VALUES ('Ä','Ccedil');
INSERT INTO Html2Ascii VALUES ('ê','Eacute');
INSERT INTO Html2Ascii VALUES ('•','Ntilde');
INSERT INTO Html2Ascii VALUES ('ô','Ouml');
INSERT INTO Html2Ascii VALUES ('†','aacute');
INSERT INTO Html2Ascii VALUES ('É','acirc');
INSERT INTO Html2Ascii VALUES ('Ö','agrave');
INSERT INTO Html2Ascii VALUES ('&','amp');
INSERT INTO Html2Ascii VALUES ('Ñ','auml');
INSERT INTO Html2Ascii VALUES ('á','ccedil');
INSERT INTO Html2Ascii VALUES ('Ç','eacute');
INSERT INTO Html2Ascii VALUES ('à','ecirc');
INSERT INTO Html2Ascii VALUES ('ä','egrave');
INSERT INTO Html2Ascii VALUES ('â','euml');
INSERT INTO Html2Ascii VALUES ('>','gt');
INSERT INTO Html2Ascii VALUES ('°','iacute');
INSERT INTO Html2Ascii VALUES ('å','icirc');
INSERT INTO Html2Ascii VALUES ('ç','igrave');
INSERT INTO Html2Ascii VALUES ('ã','iuml');
INSERT INTO Html2Ascii VALUES ('<','lt');
INSERT INTO Html2Ascii VALUES ('ï','ograve');
INSERT INTO Html2Ascii VALUES ('î','ouml');
INSERT INTO Html2Ascii VALUES (' ','nbsp');
INSERT INTO Html2Ascii VALUES ('§','ntilde');
INSERT INTO Html2Ascii VALUES ('¢','oacute');
INSERT INTO Html2Ascii VALUES ('ì','ocirc');
INSERT INTO Html2Ascii VALUES ('£','uacute');
INSERT INTO Html2Ascii VALUES ('ñ','ucirc');
INSERT INTO Html2Ascii VALUES ('ó','ugrave');
INSERT INTO Html2Ascii VALUES ('Å','uuml');
INSERT INTO Html2Ascii VALUES ('ò','yuml');

