CREATE TABLE NovellStartID (
   ID     BYTE,
   Descr  VARCHAR
);

CREATE INDEX;

INSERT INTO NovellStartID VALUES (0x01,/*AM_PM*/'Cet identificateur indique le matin ou l''aprŠs-midi (am ou pm).');
INSERT INTO NovellStartID VALUES (0x02,/*ACCESS_SERVER*/'Cet identificateur indique l''accŠs du serveur (vrai ou faux).');
INSERT INTO NovellStartID VALUES (0x03,/*DAY*/'Cet identificateur indique le num‚ro de la journ‚e.');
INSERT INTO NovellStartID VALUES (0x04,/*DAY_OF_WEEK*/'Cet identificateur indique la journ‚e de la semaine (Monday, Thuesday,...).');
INSERT INTO NovellStartID VALUES (0x05,/*DOS_REQUESTER*/'Cet identificateur indique le num‚ro de la version de Netware pour DOS.');
INSERT INTO NovellStartID VALUES (0x06,/*ERROR_LEVEL*/'Cet identificateur indique le num‚ro de l''erreur.');
INSERT INTO NovellStartID VALUES (0x07,/*FILE_SERVER*/'Cet identificateur indique le nom du serveur.');
INSERT INTO NovellStartID VALUES (0x08,/*FULL_NAME*/'Cet identificateur indique le nom complet ‚crit dans SYSCON.');
INSERT INTO NovellStartID VALUES (0x09,/*GREETING_TIME*/'Cet identificateur retourne ®morning¯, ®afternoon¯ ou ®evening¯.');
INSERT INTO NovellStartID VALUES (0x0A,/*HOUR*/'Cet identificateur indique l''heure entre 1 et 12.');
INSERT INTO NovellStartID VALUES (0x0B,/*HOUR24*/'Cet identificateur indique l''heure entre 0 et 23.');
INSERT INTO NovellStartID VALUES (0x0C,/*LOGIN_NAME*/'Cet identificateur indique le nom de l''utilisateur dans le systŠme.');
INSERT INTO NovellStartID VALUES (0x0D,/*MACHINE*/'Cet identificateur indique la machine pour l''interpr‚teur des commandes (le ®SHELL¯) (exemple: IBM_PC).');
INSERT INTO NovellStartID VALUES (0x0E,/*MEMBER OF*/'Cet identificateur indique membre d''un groupe dans le systŠme.');
INSERT INTO NovellStartID VALUES (0x0F,/*MINUTE*/'Cet identificateur indique la minute entre 0 et 59.');
INSERT INTO NovellStartID VALUES (0x10,/*MONTH*/'Cet identificateur indique le num‚ro du mois entre 1 et 12.');
INSERT INTO NovellStartID VALUES (0x11,/*MONTH_NAME*/'Cet identificateur indique le nom du mois (®January¯, ®February¯,...).');
INSERT INTO NovellStartID VALUES (0x12,/*NDAY_OF_WEEK*/'Cet identificateur indique le num‚ro du jour dans le semaine entre 1 et 7 (1 pour Dimanche).');
INSERT INTO NovellStartID VALUES (0x13,/*NETWARE_REQUESTER*/'Cet identificateur indique le num‚ro ade la version de Netware pour OS/2.');
INSERT INTO NovellStartID VALUES (0x14,/*NETWORK_ADDRESS*/'Cet identificateur indique l''adresse hexad‚cimale du r‚seau.');
INSERT INTO NovellStartID VALUES (0x15,/*NEW_MAIL*/'Cet identificateur indique YES ou NO selon l''‚tat de la variable.');
INSERT INTO NovellStartID VALUES (0x16,/*OS*/'Cet identificateur indique le systŠme d''exploitation (exemple: DRDOS).');
INSERT INTO NovellStartID VALUES (0x17,/*OS_VERSION*/'Cet identificateur indique la version de DOS (exemple: DOS V6.20).');
INSERT INTO NovellStartID VALUES (0x18,/*PASSWORD_EXPIRES*/'Cet identificateur indique le nombre de jours o— le mot de passe est encore valide.');
INSERT INTO NovellStartID VALUES (0x19,/*P_STATION*/'Cet identificateur indique le num‚ro physique de la station.');
INSERT INTO NovellStartID VALUES (0x1A,/*SECOND*/'Cet identificateur indique les secondes entre 0 et 59.');
INSERT INTO NovellStartID VALUES (0x1B,/*SHELL_TYPE*/'Cet identificateur indique le nom assign‚ … la version de Netware dans NET.CFG');
INSERT INTO NovellStartID VALUES (0x1C,/*SHORT_YEAR*/'Cet identificateur indique l''ann‚e en deux chiffres (94).');
INSERT INTO NovellStartID VALUES (0x1D,/*SMACHINE*/'Cet identificateur indique le nom assign‚ dans NET.CFG (exemple: IBM).');
INSERT INTO NovellStartID VALUES (0x1E,/*STATION*/'Cet identificateur indique le num‚ro logique de la station.');
INSERT INTO NovellStartID VALUES (0x1F,/*USER_ID*/'Cet identificateur indique le num‚ro d''identification en hexad‚cimal de l''utilisateur.');
INSERT INTO NovellStartID VALUES (0x20,/*YEAR*/'Cet identificateur indique l''ann‚e en quatre chiffres (exemple: 1994)');
