CREATE TABLE SonSortie (
   ID     BYTE PRIMARY KEY,
   Name   VARCHAR
);

CREATE INDEX;

INSERT INTO SonSortie VALUES (0x0001,'Port paralläle 1');
INSERT INTO SonSortie VALUES (0x0002,'Port paralläle 2');
INSERT INTO SonSortie VALUES (0x0003,'Sound Blaster');
INSERT INTO SonSortie VALUES (0x0004,'PC Speaker');
INSERT INTO SonSortie VALUES (0x0005,'StÇrÇo par le port paralläle 1 et 2');
INSERT INTO SonSortie VALUES (0x0006,'Sound Blaster Pro');
INSERT INTO SonSortie VALUES (0x0007,'StÇrÇo par le port paralläle 1');
INSERT INTO SonSortie VALUES (0x0008,'StÇrÇo par le port paralläle 2');
INSERT INTO SonSortie VALUES (0x0009,'Port paralläle 3');
INSERT INTO SonSortie VALUES (0x000A,'Mono par le port paralläle 1 et 2');
INSERT INTO SonSortie VALUES (0x000B,'Mono dÇfinie par l''utilisateur');
INSERT INTO SonSortie VALUES (0x000C,'StÇrÇo dÇfinie par l''utilisateur');
INSERT INTO SonSortie VALUES (0x000D,'Disney-Sound par le port paralläle 1');
INSERT INTO SonSortie VALUES (0x000E,'Disney-Sound par le port paralläle 2');
INSERT INTO SonSortie VALUES (0x000F,'Disney-Sound par le port paralläle 3');
INSERT INTO SonSortie VALUES (0x0010,'Quadrophonique par le port paralläle 1');
INSERT INTO SonSortie VALUES (0x0011,'AdLib');
INSERT INTO SonSortie VALUES (0x0012,'GUS (Gravis Ultra Sound)');
INSERT INTO SonSortie VALUES (0x0013,'Roland MPU 401');
INSERT INTO SonSortie VALUES (0x0014,'Tandy Digital');

