CREATE TABLE Langues (
   ID   WORD PRIMARY KEY,
   NomF VARCHAR,
   NomA VARCHAR
);

CREATE INDEX;

INSERT INTO Langues VALUES (0x0000,'Anglais',   'English');
INSERT INTO Langues VALUES (0x0001,'Fran‡ais',  'French');
INSERT INTO Langues VALUES (0x0002,'Hollandais','Dutch');
INSERT INTO Langues VALUES (0x0003,'Allemand',  'German');
INSERT INTO Langues VALUES (0x0004,'Su‚dois',   'Swedish');
INSERT INTO Langues VALUES (0x0005,'Finlandais','Finnish');
INSERT INTO Langues VALUES (0x0006,'Espagnol',  'Spanish');
INSERT INTO Langues VALUES (0x0007,'Portuguais','Portuguese');
INSERT INTO Langues VALUES (0x0008,'Italien',   'Italian');

