CREATE TABLE BasicFonctionStr (
   ID     BYTE,
   Name   VARCHAR,
   Params VARCHAR
);

CREATE INDEX;

INSERT INTO BasicFonctionStr VALUES (0x12,'APP','.');
INSERT INTO BasicFonctionStr VALUES (0x01,'BIN$','(I)');
INSERT INTO BasicFonctionStr VALUES (0x02,'CHR','(I)');
INSERT INTO BasicFonctionStr VALUES (0x02,'CHR$','(I)');
INSERT INTO BasicFonctionStr VALUES (0x1A,'CONVCHAINE','(S,I)');
INSERT INTO BasicFonctionStr VALUES (0x19,'CURDIR','(S)');
INSERT INTO BasicFonctionStr VALUES (0x1C,'DATE$','');
INSERT INTO BasicFonctionStr VALUES (0x03,'ENVIRON','(S)');
INSERT INTO BasicFonctionStr VALUES (0x03,'ENVIRON$','(S)');
INSERT INTO BasicFonctionStr VALUES (0x1D,'ERDESCR$','');
INSERT INTO BasicFonctionStr VALUES (0x0A,'ESPACE','(I)');
INSERT INTO BasicFonctionStr VALUES (0x13,'FILELISTBOX','(S,S)');
INSERT INTO BasicFonctionStr VALUES (0x06,'GAUCHE','(S,I)');
INSERT INTO BasicFonctionStr VALUES (0x04,'HEX','(I)');
INSERT INTO BasicFonctionStr VALUES (0x04,'HEX$','(I)');
INSERT INTO BasicFonctionStr VALUES (0x05,'INKEY$','');
INSERT INTO BasicFonctionStr VALUES (0x11,'INPUTBOX','(S,S)');
INSERT INTO BasicFonctionStr VALUES (0x0D,'LCASE','(S)');
INSERT INTO BasicFonctionStr VALUES (0x06,'LEFT','(S,I)');
INSERT INTO BasicFonctionStr VALUES (0x06,'LEFT$','(S,I)');
INSERT INTO BasicFonctionStr VALUES (0x0F,'LTRIM','(S)');
INSERT INTO BasicFonctionStr VALUES (0x0E,'MAJUSCULE','(S)');
INSERT INTO BasicFonctionStr VALUES (0x0D,'MINUSCULE','(S)');
INSERT INTO BasicFonctionStr VALUES (0x07,'MID','(S,I|,I)');
INSERT INTO BasicFonctionStr VALUES (0x07,'MID$','(S,I|,I)');
INSERT INTO BasicFonctionStr VALUES (0x14,'MKI$','(I)');
INSERT INTO BasicFonctionStr VALUES (0x15,'MKL$','(I)');
INSERT INTO BasicFonctionStr VALUES (0x0B,'NUMCHAINE','(I)');
INSERT INTO BasicFonctionStr VALUES (0x08,'OCT$','(I)');
INSERT INTO BasicFonctionStr VALUES (0x19,'REPERCOUR','(S)');
INSERT INTO BasicFonctionStr VALUES (0x18,'REQUEST','');
INSERT INTO BasicFonctionStr VALUES (0x09,'RIGHT','(S,I)');
INSERT INTO BasicFonctionStr VALUES (0x09,'RIGHT$','(S,I)');
INSERT INTO BasicFonctionStr VALUES (0x10,'RTRIM','(S)');
INSERT INTO BasicFonctionStr VALUES (0x0A,'SPACE','(I)');
INSERT INTO BasicFonctionStr VALUES (0x0A,'SPACE$','(I)');
INSERT INTO BasicFonctionStr VALUES (0x0B,'STR','(I)');
INSERT INTO BasicFonctionStr VALUES (0x0B,'STR$','(I)');
INSERT INTO BasicFonctionStr VALUES (0x1A,'STRCONV','(S,I)');
INSERT INTO BasicFonctionStr VALUES (0x0C,'STRING$','');
INSERT INTO BasicFonctionStr VALUES (0x0A,'TAB','(I)');
INSERT INTO BasicFonctionStr VALUES (0x1B,'TRIM','(S)');
INSERT INTO BasicFonctionStr VALUES (0x0E,'UCASE','(S)');
INSERT INTO BasicFonctionStr VALUES (0x0E,'UPS$','(S)');

