CREATE TABLE CompilateurExtensior (
   ID        WORD,
   Extension VARCHAR,
   Parent    VARCHAR
);

CREATE INDEX;

INSERT INTO CompilateurExtensior VALUES (    1,'.ASM','TASM.EXE;A86.EXE;MASM.EXE');
INSERT INTO CompilateurExtensior VALUES (    2,'.ASP','');
INSERT INTO CompilateurExtensior VALUES (    3,'.BAS','');
INSERT INTO CompilateurExtensior VALUES (    4,'.BAT','');
INSERT INTO CompilateurExtensior VALUES (    5,'.BTM','');
INSERT INTO CompilateurExtensior VALUES (    6,'.C',  'BCC.EXE;TCC.EXE;GCC.EXE;CL.EXE;LINT.EXE');
INSERT INTO CompilateurExtensior VALUES (    7,'.CAS','BCC.EXE;TCC.EXE;GCC.EXE;CL.EXE;LINT.EXE');
INSERT INTO CompilateurExtensior VALUES (    8,'.CBL','COBOL.EXE');
INSERT INTO CompilateurExtensior VALUES (    9,'.CC', 'BCC.EXE;TCC.EXE;GCC.EXE;CL.EXE;LINT.EXE');
INSERT INTO CompilateurExtensior VALUES (   10,'.COM','');
INSERT INTO CompilateurExtensior VALUES (   11,'.CPP','BCC.EXE;TCC.EXE;GCC.EXE;CL.EXE;LINT.EXE');
INSERT INTO CompilateurExtensior VALUES (   12,'.CUT','VPIC.EXE;CSHOW.EXE;PVE.EXE');
INSERT INTO CompilateurExtensior VALUES (   13,'.DAT','');
INSERT INTO CompilateurExtensior VALUES (   14,'.DBF','');
INSERT INTO CompilateurExtensior VALUES (   15,'.EXE','');
INSERT INTO CompilateurExtensior VALUES (   16,'.F77','F77.EXE');
INSERT INTO CompilateurExtensior VALUES (   17,'.FOR','F77.EXE');
INSERT INTO CompilateurExtensior VALUES (   18,'.H',  'BCC.EXE;TCC.EXE;GCC.EXE;CL.EXE;LINT.EXE');
INSERT INTO CompilateurExtensior VALUES (   19,'.HAM','VPIC.EXE;CSHOW.EXE;PVE.EXE');
INSERT INTO CompilateurExtensior VALUES (   20,'.HPP','BCC.EXE;TCC.EXE;GCC.EXE;CL.EXE;LINT.EXE');
INSERT INTO CompilateurExtensior VALUES (   21,'.IFF','VPIC.EXE;CSHOW.EXE;PVE.EXE');
INSERT INTO CompilateurExtensior VALUES (   22,'.JPG','VPIC.EXE;CSHOW.EXE;PVE.EXE');
INSERT INTO CompilateurExtensior VALUES (   23,'.LGO','');
INSERT INTO CompilateurExtensior VALUES (   32,'.MGC','');
INSERT INTO CompilateurExtensior VALUES (   24,'.OBJ','LINK.EXE;TLINK.EXE');
INSERT INTO CompilateurExtensior VALUES (   25,'.PAS','BPC.EXE;TPC.EXE;QPL.COM;PC.EXE');
INSERT INTO CompilateurExtensior VALUES (   26,'.PIC','VPIC.EXE;CSHOW.EXE;PVE.EXE');
INSERT INTO CompilateurExtensior VALUES (   27,'.RC', '');
INSERT INTO CompilateurExtensior VALUES (   28,'.RIX','VPIC.EXE;CSHOW.EXE;PVE.EXE');
INSERT INTO CompilateurExtensior VALUES (   29,'.SQL','');
INSERT INTO CompilateurExtensior VALUES (   30,'.TAR','VPIC.EXE;CSHOW.EXE;PVE.EXE');
INSERT INTO CompilateurExtensior VALUES (   31,'.TGA','VPIC.EXE;CSHOW.EXE;PVE.EXE');
INSERT INTO CompilateurExtensior VALUES (   33,'.XLS','');

