CREATE TABLE Etat (
   ID        WORD,
   EtatF     VARCHAR,
   EtatA     VARCHAR,
   IDCountry SMALLINT

);

CREATE INDEX;

INSERT INTO Etat VALUES (110,'Angleterre',       'Angleterre',-1);
INSERT INTO Etat VALUES (120,'Ile de Man',       'Ile de Man',-1);
INSERT INTO Etat VALUES (140,'Irlande du Nord',  'North Irlande',-1);
INSERT INTO Etat VALUES (160,'êcosse',           'Scotland',-1);
INSERT INTO Etat VALUES (180,'Wales',            'Wales',-1);
