CREATE TABLE Province (
   ID        WORD,
   ProvinceF VARCHAR,
   ProvinceA VARCHAR,
   IDCountry SMALLINT
);

CREATE INDEX;

INSERT INTO Province VALUES (0x0001,'Alberta',              'Alberta',-1);
INSERT INTO Province VALUES (0x0002,'Colombie-Britanique',  'British Columbia',-1);
INSERT INTO Province VALUES (0x0003,'Ile-du-Prince-êdouard','Prince Edward Island',-1);
INSERT INTO Province VALUES (0x0004,'Manitoba',             'Manitoba',-1);
INSERT INTO Province VALUES (0x0005,'Nouveau-Brunswick',    'New Brunswick',-1);
INSERT INTO Province VALUES (0x0006,'Nouvelle-êcosse',      'Nova Scotia',-1);
INSERT INTO Province VALUES (0x0007,'Ontario',              'Ontario',-1);
INSERT INTO Province VALUES (0x0008,'QuÇbec',               'Quebec',5700);
INSERT INTO Province VALUES (0x0009,'Saskatchewan',         'Saskatchewan',-1);
INSERT INTO Province VALUES (0x000A,'Terre-Neuve/Labrador', 'Terre-Neuve/Labrador',-1);
INSERT INTO Province VALUES (0x000B,'Territoire du Yukon',  'Yukon Territory',-1);
