' Ce programme indique comment connaitre la largeur de l'‚cran ou de la fenˆtre (Forms)
'en utilisant les fonctions du ®Basic Pro¯ du MonsterBook.

PRINT "Largeur de l'‚cran ou de la fenˆtre = "+WIDTH
PRINT "Appuyer sur une touche pour retourner..."
K%=READKEY
                                                                                                                                                                                                       ÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏÏ
