CREATE TABLE Auteurs (
   NoAuteur   INTEGER,
   Prenom     VARCHAR,
   Nom        VARCHAR
);

CREATE INDEX;

INSERT INTO Auteurs VALUES ( 10000000,'G.',       'Badoux');
INSERT INTO Auteurs VALUES ( 20000000,'D.',       'Bloem');
INSERT INTO Auteurs VALUES ( 30000000,'M.',       'Calberg');
INSERT INTO Auteurs VALUES ( 40000000,'Ph.',      'Daumerie');
INSERT INTO Auteurs VALUES ( 50000000,'B.',       'Fara');
INSERT INTO Auteurs VALUES ( 60000000,'C.',       'Gilles');
INSERT INTO Auteurs VALUES ( 70000000,'Van',      'Gilluwe');
INSERT INTO Auteurs VALUES ( 80000000,'B‚n‚dicte','Hudault');
INSERT INTO Auteurs VALUES ( 90000000,'N.',       'Kother');
INSERT INTO Auteurs VALUES (100000000,'L‚opold',  'Laurent');
INSERT INTO Auteurs VALUES (110000000,'P.',       'Lefevre');
INSERT INTO Auteurs VALUES (120000000,'C.',       'L‚onard');
INSERT INTO Auteurs VALUES (130000000,'G.',       'Liegois');
INSERT INTO Auteurs VALUES (140000000,'M.',       'Mennig');
INSERT INTO Auteurs VALUES (150000000,'Philippe', 'Mercier');
INSERT INTO Auteurs VALUES (160000000,'J.',       'Morleghem');
INSERT INTO Auteurs VALUES (170000000,'Gilles',   'Ouellet');
INSERT INTO Auteurs VALUES (180000000,'F.',       'Otwaschkau');
INSERT INTO Auteurs VALUES (190000000,'A.',       'Ravet');
INSERT INTO Auteurs VALUES (200000000,'Suzanne',  'Rivard');
INSERT INTO Auteurs VALUES (210000000,'Jean',     'Talbot');
INSERT INTO Auteurs VALUES (220000000,'Robert',   'Van Loo');
INSERT INTO Auteurs VALUES (230000000,'',         'Virga');
INSERT INTO Auteurs VALUES (240000000,'I.',       'Virgatchik');
INSERT INTO Auteurs VALUES (250000000,'J.P.',     'Vuylsteke');
INSERT INTO Auteurs VALUES (260000000,'A.',       'Wiard');
