(***************************************************************************)
(*                                                                         *)
(*                            Maitre Version 2.00A                         *)
(*                                                                         *)
(*                          Copyright (C) 1990 par                         *)
(*                 Les Chavaliers de Malte International                   *)
(*                                                                         *)
(***************************************************************************)

Const Vrai = True;
      Faux = False;

Type Chemin       = String[64];
     String4      = String[4];
     String8      = String[8];
     String12     = String[12];
     String16     = String[16];
     String20     = String[20];
     String24     = String[24];
     String28     = String[28];
     String32     = String[32];
     String36     = String[36];
     String40     = String[40];
     String44     = String[44];
     String48     = String[48];
     String64     = String[64];
     String127    = String[128];
     String132    = String[132];
     String255    = String[255];

Var Registre : Registers;
    Erreur   : Integer;


